# PATH is extended in .zprofile

export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export DEV_HOME="$HOME/Development"
export FVM_HOME="$HOME/.fvm"
export FLUTTER_HOME="$FVM_HOME/default"
# Explicitly define HISTFILE because Android Studio / IntellJ IDEA has a bug
# https://youtrack.jetbrains.com/issue/IDEA-204243#focus=streamItem-27-3241279-0-0
export HISTFILE="$HOME/.zsh_history"
export HOMEBREW_NO_ANALYTICS=1
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export EDITOR="/usr/local/bin/vim"

# .zshenv.secret contains sensitive environment variables with API keys etc.
source $HOME/.zshenv.secret
