# Configuration for "Oh My Zsh" nvm plugin
NVM_AUTOLOAD=1

## Antigen
# Install with "brew install antigen"
source /usr/local/share/antigen/antigen.zsh
antigen init $HOME/.antigenrc

## Google Cloud SDK
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

## Aliases
# Fix ls colors because we're using GNU coreutils
alias ls="ls --color=auto"

## Miscellaneous
# Temporary fix for white-on-white paste in Hyper terminal
#unset zle_bracketed_paste

source $HOME/.dotfiles/zsh/inc/zsh-autosuggestions-paste-fix.zsh

## sdkman
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
