# Configuration for "Oh My Zsh" nvm plugin
NVM_AUTOLOAD=1

## Zsh
setopt auto_cd
setopt share_history
setopt auto_pushd
setopt hist_expire_dups_first
setopt hist_reduce_blanks
setopt hist_verify
zstyle ':completion:*' menu select

## Zplug
# Install with "brew install zplug"
source $HOME/.zplug.zsh

## Google Cloud SDK
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

## Aliases
# Fix ls colors because we're using GNU coreutils
alias ls="ls --color=auto"
alias f="fuck"

## Miscellaneous
source $HOME/.dotfiles/zsh/inc/zsh-autosuggestions-paste-fix.zsh

## sdkman
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
