# Antigen
# Install with "brew install antigen"
source /usr/local/share/antigen/antigen.zsh
antigen init $HOME/.antigenrc

# nvm
source $HOME/.dotfiles/zsh/inc/nvm-hook.zsh

# Google Cloud SDK
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# Fix ls colors because we're using GNU coreutils
alias ls="ls --color=auto"
